name: testes_cwi
description: "Let's test (Tech Talk)"
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true